#=================================================
# Description: Build ubports for dream2lte using GitHub Actions
# Licence: MIT
# Contributor: 0312birdzhang
# Maintainer: Danct12
# Credit: https://github.com/P3TERX/Actions-OpenWrt
#=================================================

name: Build System Image

on: 
  push:
    branches:
      - master
  release:
    types: [published]

jobs:

  build:
    runs-on: ubuntu-20.04

    env:
      VENDOR: samsung
      DEVICE: dream2lte
      ANDROID_ROOT: /home/runner/work/halium/

    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Initialization environment
      run: |
        sudo apt-get update
        sudo apt-get install -y \
        openjdk-8-jdk android-tools-adb bc \
        bison build-essential curl flex g++-multilib \
        gcc-multilib gnupg gperf imagemagick lib32ncurses5-dev \
        lib32readline-dev lib32z1-dev liblz4-tool \
        libncurses5-dev libsdl1.2-dev libssl-dev \
        libxml2 libxml2-utils lzop pngcrush rsync schedtool \
        squashfs-tools xsltproc yasm zip zlib1g-dev git python3.7
        sudo docker rmi `docker images -q`
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        mkdir -p ~/bin
        wget 'https://storage.googleapis.com/git-repo-downloads/repo' -P ~/bin
        chmod +x ~/bin/repo
        git config --global user.name "UBports Galaxy S8+ CI"
        git config --global user.email "thisemaildoesnotexist@exist.com"

    - name: Downloading source code
      run: |
        source halium.env
        mkdir -p $ANDROID_ROOT
        cd $ANDROID_ROOT
        repo init -u https://github.com/Halium/android -b halium-9.0 --depth=1
        mkdir -p $ANDROID_ROOT/.repo/local_manifests
        # will uncomment once merge request accepted on halium repo for manifest
        #wget https://raw.githubusercontent.com/Halium/halium-devices/halium-9.0/manifests/"$VENDOR"_"$DEVICE".xml -O $ANDROID_ROOT/.repo/local_manifests/$DEVICE.xml
        wget https://gist.githubusercontent.com/Parmjot-Singh/f629bdc8cbb4a3cf93a3e65a2450f384/raw/b2f45fc6ac8240e33c07eb61e02c88dccc1ceb13/manifest.xml -O $ANDROID_ROOT/.repo/local_manifests/device.xml
        repo sync -j8 -c --no-clone-bundle --no-tags
    
    - name: Build HAL
      run: |
        sudo apt update
        sudo apt autoremove python3 -y
        sudo apt install android-tools-mkbootimg bc bison build-essential ca-certificates cpio curl flex git kmod libssl-dev libtinfo5 python2 sudo unzip wget xz-utils -y --no-install-recommends
        sudo ln -sf python2.7 /usr/bin/python
        chmod +x build-hal.sh
        bash -x build-hal.sh
      shell: bash
    
    - name : Upload boot image
      uses: actions/upload-artifact@master
      with:
        name: hybris-boot image
        path: /home/runner/work/halium/out/target/product/dream2lte/hybris-boot.img

    - name : Upload boot image
      uses: actions/upload-artifact@master
      with:
        name: halium-boot image
        path: /home/runner/work/halium/out/target/product/dream2lte/halium-boot.img

    - name : Upload recovery image
      uses: actions/upload-artifact@master
      with:
        name: Recovery image
        path: /home/runner/work/halium/out/target/product/dream2lte/recovery.img

    - name : Upload system image
      uses: actions/upload-artifact@master
      with:
        name: System image
        path: /home/runner/work/halium/out/target/product/dream2lte/system.img
