#=================================================
# Description: Build ubports for dream2lte using GitHub Actions
# Licence: MIT
# Contributor: 0312birdzhang
# Maintainer: Danct12
# Credit: https://github.com/P3TERX/Actions-OpenWrt
#=================================================

name: Build System Image
on: 
  push:
    branches:
      - master
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-20.04

    env:
      VENDOR: samsung
      DEVICE: dream2lte
      ANDROID_ROOT: /home/runner/work/halium/

    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Initialise runner machine
      run: |
        sudo apt-get update
        sudo apt-get install -y \
        openjdk-8-jdk android-tools-adb bc \
        bison build-essential curl flex g++-multilib \
        gcc-multilib gnupg gperf imagemagick lib32ncurses5-dev \
        lib32readline-dev lib32z1-dev liblz4-tool \
        libncurses5-dev libsdl1.2-dev libssl-dev \
        libxml2 libxml2-utils lzop pngcrush rsync schedtool \
        squashfs-tools xsltproc yasm zip zlib1g-dev git python3.7
        sudo docker rmi `docker images -q`
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        mkdir -p ~/bin
        wget 'https://storage.googleapis.com/git-repo-downloads/repo' -P ~/bin
        chmod +x ~/bin/repo
        git config --global user.name "UBports Galaxy S8+ CI"
        git config --global user.email "thisemaildoesnotexist@exist.com"

    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@v1.1.0
      with:
        tool-cache: true
        
        android: false
        dotnet: true
        haskell: true
        large-packages: false
        swap-storage: true
    
    - name: Download source code
      run: |
        source halium.env
        mkdir -p $ANDROID_ROOT
        cd $ANDROID_ROOT
        repo init -u https://github.com/Halium/android -b halium-9.0 --depth=1
        mkdir -p $ANDROID_ROOT/.repo/local_manifests
        # will uncomment once merge request accepted on halium repo for manifest
        #wget https://raw.githubusercontent.com/Halium/halium-devices/halium-9.0/manifests/"$VENDOR"_"$DEVICE".xml -O $ANDROID_ROOT/.repo/local_manifests/$DEVICE.xml
        wget https://gist.githubusercontent.com/Parmjot-Singh/f629bdc8cbb4a3cf93a3e65a2450f384/raw/b2f45fc6ac8240e33c07eb61e02c88dccc1ceb13/manifest.xml -O $ANDROID_ROOT/.repo/local_manifests/device.xml
        repo sync -j8 -c --no-clone-bundle --no-tags
    
    - name: Install build dependencies
      run: |
        sudo apt update
        sudo apt autoremove python3 -y
        sudo apt install -y --no-install-recommends \
        openjdk-8-jdk android-tools-adb android-tools-mkbootimg bc \
        bison build-essential ca-certificates cpio curl flex g++-multilib \
        gcc-multilib gnupg gperf imagemagick kmod lib32ncurses5-dev \
        lib32readline-dev lib32z1-dev libelf-dev liblz4-tool \
        libncurses5-dev libsdl1.2-dev libssl-dev libtinfo5 \
        libxml2 libxml2-utils lzop ncurses-dev pngcrush python2 rsync schedtool \
        squashfs-tools unzip wget xsltproc xz-utils yasm zip zlib1g-dev git
        
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        
        sudo ln -sf python2.7 /usr/bin/python
        chmod +x save-storage.sh
        bash -x save-storage.sh

    - name: Initialise build environment
      run: |
        chmod +x init-build-env.sh
        bash -x init-build-env.sh
    
#    - name: Build Hybris Boot image
#      run: |
#        chmod +x build-hybris.sh
#        bash -x build-hybris.sh
#      shell: bash
#    
#    - name : Upload Hybris Boot image
#      uses: actions/upload-artifact@master
#      with:
#        name: hybris-boot image
#        path: /home/runner/work/halium/out/target/product/dream2lte/hybris-boot.img
#
    - name: Build Halium Boot image
      run: |
        chmod +x build-halium.sh
        bash -x build-halium.sh
      shell: bash

    - name : Upload Halium Boot image
      uses: actions/upload-artifact@master
      with:
        name: halium-boot.img
        path: /home/runner/work/halium/out/target/product/dream2lte/halium-boot.img

    - name: Build System image
      run: |
        chmod +x build-system.sh
        bash -x build-system.sh
      shell: bash

    - name : Upload System image
      uses: actions/upload-artifact@master
      with:
        name: system.img
        path: /home/runner/work/halium/out/target/product/dream2lte/system.img

    - name: Build Recovery image
      run: |
        chmod +x build-recovery.sh
        bash -x build-recovery.sh
      shell: bash

    - name : Upload Recovery image
      uses: actions/upload-artifact@master
      with:
        name: recovery.img
        path: /home/runner/work/halium/out/target/product/dream2lte/recovery.img
